apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: openshift-operators
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: latest
  installPlanApproval: Manual
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  state: AtLatestKnown
